import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
    sidebar,
}: Readonly<{
    children: React.ReactNode;
    sidebar: React.ReactNode;
}>) {
    return (
        <div className="relative mx-auto flex w-full max-w-screen-2xl lg:gap-x-4">
            {/* Sidebar */}

            {/* Main Content */}
            <div className="sticky top-32 hidden h-full max-h-screen w-96 overflow-y-scroll lg:block">
                {sidebar}
            </div>
            <div className="w-full">{children}</div>
        </div>
    );
}
