import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
    sidebar,
}: Readonly<{
    children: React.ReactNode;
    sidebar: React.ReactNode;
}>) {
    return (
        <div className="relative mx-auto flex w-full max-w-[1575px] flex-col lg:flex-row">
            {/* Sidebar */}
            <div className="sticky top-32 hidden h-fit w-fit lg:block lg:w-96">
                <div className="max-h-[calc(100%_-_190px)] overflow-y-auto">
                    {sidebar}
                </div>
            </div>

            {/* Main Content */}
            <div className="w-full">{children}</div>
        </div>
    );
}
